"""Download Google Fonts as self-hosted woff2 + emit a local @font-face sheet.

Fetches the css2 API with a modern browser UA so we get woff2 (not ttf),
keeps only the latin subset, and rewrites src urls to local paths.
"""
import os
import re
import urllib.request

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "assets", "fonts")
CSS_OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "css", "fonts.css")

# family spec -> css2 query fragment
FAMILIES = [
    ("Instrument+Serif:ital,wght@0,400;1,400", "InstrumentSerif"),
    ("Inter:wght@100..900", "Inter"),
    # variable axis: one file instead of a static cut per weight
    ("JetBrains+Mono:wght@100..800", "JetBrainsMono"),
]

# Google's css2 emits one @font-face block per unicode-range. The site copy is
# English, so latin alone is sufficient -- dropping cyrillic/greek/vietnamese/
# latin-ext roughly halves the payload.
KEEP_SUBSETS = ("latin",)


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read().decode("utf-8")


def block_subset(comment: str) -> str:
    """The /* latin */ comment precedes the @font-face block it labels."""
    m = re.search(r"/\*\s*([a-z\-]+)\s*\*/", comment)
    return m.group(1) if m else ""


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(CSS_OUT), exist_ok=True)

    sheet = [
        "/* =========================================================",
        "   BlueFluteX — self-hosted fonts (generated by tools/fetch-fonts.py)",
        "   Instrument Serif  — SIL Open Font License 1.1",
        "   Inter             — SIL Open Font License 1.1",
        "   JetBrains Mono    — SIL Open Font License 1.1",
        "   Do not edit by hand; re-run the script to refresh.",
        "   ========================================================= */",
        "",
    ]

    total = 0
    for spec, slug in FAMILIES:
        css = fetch(f"https://fonts.googleapis.com/css2?family={spec}&display=swap")
        # Split into (preceding comment, @font-face block) pairs
        chunks = re.findall(r"(/\*\s*[a-z\-]+\s*\*/)\s*(@font-face\s*\{.*?\})", css, re.S)

        for comment, block in chunks:
            subset = block_subset(comment)
            if subset not in KEEP_SUBSETS:
                continue

            urls = re.findall(r"url\((https://[^)]+\.woff2)\)", block)
            if not urls:
                continue

            # name: family + style + weight + subset
            style = re.search(r"font-style:\s*(\w+)", block).group(1)
            weight = re.search(r"font-weight:\s*([\d ]+)", block).group(1).strip()
            weight = weight.replace(" ", "-")

            for url in urls:
                fname = f"{slug}-{style}-{weight}-{subset}.woff2"
                dest = os.path.join(OUT_DIR, fname)
                if not os.path.exists(dest):
                    req = urllib.request.Request(url, headers={"User-Agent": UA})
                    with urllib.request.urlopen(req, timeout=60) as r, open(dest, "wb") as f:
                        f.write(r.read())
                size = os.path.getsize(dest)
                total += size
                block = block.replace(url, f"../fonts/{fname}")

            sheet.append(block)
            sheet.append("")

        print(f"{slug}: done")

    with open(CSS_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(sheet))

    print(f"\nfonts.css -> {CSS_OUT}")
    print(f"total woff2 payload: {total/1024:.1f} KB")


if __name__ == "__main__":
    main()